### ISSUE TITLE
Add businessvalue, relativepenalty and easeofrealization to project-add-component

### ISSUE THREAD

**Issue by acevikel** [Winbook-USC/winbook-app#54]
Currently these values are ignored for the project input. They need to be considered when creating a project

**Comment by yzheng988** [comment]
I think these three values are part of the form in the frontend HTML, can you check again?

**Comment by yzheng988** [comment]
The backend SQL schema for the project does not have these values as part of the schema. Only businessValueWeight, relativePenaltyWeight, and easeOfRealizationWeight. Do we need to change backend schema for this to be implemented?

**Comment by acevikel** [comment]
They are actually the values that I have mentioned. There is a weight at the end of the key just to make the distinction that it is a key for the project, not win condition. So, no need to make changes, they are the values that we need to update

**Comment by yzheng988** [comment]
PR #109
