### ISSUE TITLE
Writing a comment to a win-condition hides the comments

### ISSUE THREAD

**Issue by acevikel** [Winbook-USC/winbook-app#61]
When a new comment is posted, it hides the comments, and it shouldn't

**Comment by romialsaid** [comment]
When a new comment is added, the win conditions are rendered again, causing it to initialize to showComments = false again. A way to solve this can be to only show the comment on the front end, and save it to the backend when the page is refreshed. Any other suggestions or opinions?

**Comment by acevikel** [comment]
I'm not sure how we can handle every page refresh robustly in angular. Two solutions I can think of:

1-) Easier frontend+backend solution. Return comment data from backend whenever a new comment is added. Pass wincondition object to the service when creating a comment rather than wincondition id, and add resulting comment to that wincondition.

2-) Cumbersome pure frontend solution. Hold comment shown state in wincondition service rather than wincondition object. 

I tried approach 1, and created a hacky solution. See my pr
