### ISSUE TITLE
Profile page backend integration

### ISSUE THREAD

**Issue by acevikel** [Winbook-USC/winbook-app#71]
Profile page just shows dummy data, and it has to be integrated with the backend, possibly over a profile service

**Comment by hahnalex** [comment]
Currently working on this issue. So far, I've added the basic Profile service, with functionality to GET user data from the backend and display it on the Profile page. 

Next, I need to implement the logic to get user input from the Profile page form, and POST any changes to the backend.

**Comment by hahnalex** [comment]
The Profile Service is done, EXCEPT for profile pictures. 
We still need to figure out how we will transmit, store, and load the image files.
