### ISSUE TITLE
New win condition posted to the end

### ISSUE THREAD

**Issue by romialsaid** [Winbook-USC/winbook-app#93]
When a new win condition is posted, it is appended to the end of the page, so it is not clear if it was posted or not. We should either add a feedback such as "Your win condition was posted." or a better solution would be to list the win conditions according to chronologically recent so it shows up at the top.

**Comment by acevikel** [comment]
Good point. We are currently fetching all the win conditions after wc creation, which is an unnecessary load for the server. The backend should return correctly the newly created win condition after win condition creation. In this case, another approach would be to add a new flag to the returned win condition data and push it to the win condition array. Then when sorting win conditions, we can put the win conditions with the new flag to the beginning.  Moreover, in win-condition object, we can add a timer, like if the wincondition.new is True, then set the color of it to yellow, and after 5 seconds, set wincondition.new to false and then remove the yellow color. So in practice newly posted winconditions should appear in the top of the list and then blend inside others after 5 seconds
